# Dockerfile para o Firewall
FROM alpine:latest

# Instala iptables
RUN apk add --no-cache iptables

# Copia o script de configuração do firewall
COPY firewall.sh /firewall.sh
RUN chmod +x /firewall.sh

# Executa o script na inicialização
CMD ["/firewall.sh"]
