
services:
  # Serviço do banco de dados principal (master)
  db:
    image: postgres:${POSTGRES_IMAGE_VERSION}
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/master/init:/docker-entrypoint-initdb.d
    networks:
      - pi_network

  # Serviço da API
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    tty: true
    networks:
      - pi_network

  # Serviços web com NGINX
  web1:
    image: nginx:latest
    container_name: web1
    volumes:
      - ./WEB/html:/usr/share/nginx/html
    networks:
      - pi_network

  web2:
    image: nginx:latest
    container_name: web2
    volumes:
      - ./WEB/html:/usr/share/nginx/html
    networks:
      - pi_network

  # NGINX reverso para balancear carga entre web1 e web2
  nginx:
    build: 
      context: ./WEB
      dockerfile: Dockerfile
    image: nginx:${NGINX_IMAGE_VERSION}
    container_name: nginx-container
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
    networks:
      - pi_network

  k6:
     build:
       context: ./k6-tester 
       dockerfile: Dockerfile  
     depends_on:
       - nginx  
     networks:
       - pi_network


volumes:
  db_data:
  

networks:
  pi_network:
