services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/nginx.conf
    depends_on:
      - web1
      - web2
