global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodes'
    static_configs:
      - targets: 
        - 'node-exporter1:9100'
        - 'node-exporter2:9100'
        - 'node-exporter3:9100'
        - 'node-exporter4:9100'
        - 'node-exporter5:9100'
