apiVersion: v1
kind: Service
metadata:
  name: api-app-service
spec:
  type: LoadBalancer
  selector:
    app: PiCloud
    tier: api-app
    environment: dev
  ports:
    - port: 8080
      targetPort: 8080
      
