x-postgres-common:
  &postgres-common
  image: postgres:14-alpine
  restart: always
  healthcheck:
    test: 'pg_isready -U test --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pi_network

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      - pi_network
  
  data_collector:
    build:
      context: ./data_collector
      dockerfile: Dockerfile
    container_name: data_collector
    volumes:
      - ./data_collector/prometheus_data:/app/prometheus_data
    ports:
      - "8001:8001" 
    networks:
      - pi_network
    environment:
      - PROMETHEUS_URL=http://prometheus:9090  # Variável de ambiente para o endereço do Prometheus

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   # volumes:
  #   #   - ./grafana/provisioning:/etc/grafana/provisioning
  #   #   - ./grafana/dashboards:/var/lib/grafana/dashboards
  #   networks:
  #     - pi_network

  # node_exporter:
  #     image: prom/node-exporter
  #     container_name: node_exporter
  #     ports:
  #       - "9100:9100"
  #     networks:
  #       - pi_network
  
  db:
    <<: *postgres-common
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    user: postgres
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on
    volumes:
      - ./DB/scripts/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    networks:
      - pi_network

  db-replica:
    <<: *postgres-common
    ports:
      - 5433:5432
    environment:
      PGUSER: reptest
      PGPASSWORD: test
    user: postgres
    command: |
      bash -c "
      rm -rf /var/lib/postgresql/data/*
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=db --port=5432
      do
        echo 'Waiting for primary to connect...'
        sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres 
      "
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - db_replica_data:/var/lib/postgresql/data
    networks:
      - pi_network

  # Serviço da API
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api-container
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PORT=8080
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
    tty: true
    networks:
      - pi_network


  # Node de Armazenamento
  node1:
    build:
      context: ./NODE
      dockerfile: Dockerfile
    container_name: node1-container
    environment:
      - NODE_ID=node1
      - NODE_PORT=8082
      - DATA_COLLECTOR_URL=http://data_collector:8001/receive_metrics
      - PROMETHEUS_URL=http://prometheus:9090
      - INSTANCE_LABEL=node-exporter1:9100
    ports:
      - "8082:8082"
    networks:
      - pi_network  # Conectado à mesma rede que a API para comunicação
    
  
  node-exporter1:
    image: prom/node-exporter
    container_name: node-exporter1
    ports:
      - "9101:9100"
    networks:
      - pi_network

  node2:
    build:
      context: ./NODE
      dockerfile: Dockerfile
    container_name: node2-container
    environment:
      - NODE_ID=node2
      - NODE_PORT=8082
      - DATA_COLLECTOR_URL=http://data_collector:8001/receive_metrics
      - PROMETHEUS_URL=http://prometheus:9090
      - INSTANCE_LABEL=node-exporter2:9100
    ports:
      - "8083:8082"
    networks:
      - pi_network
    depends_on:
      - node1
  node-exporter2:
    image: prom/node-exporter
    container_name: node-exporter2
    ports:
      - "9100"
    networks:
      - pi_network

  node3:
    build:
      context: ./NODE
      dockerfile: Dockerfile
    container_name: node3-container
    environment:
      - NODE_ID=node3
      - NODE_PORT=8082
      - DATA_COLLECTOR_URL=http://data_collector:8001/receive_metrics
      - PROMETHEUS_URL=http://prometheus:9090
      - INSTANCE_LABEL=node-exporter3:9100
    ports:
      - "8084:8082"
    networks:
      - pi_network
    depends_on:
      - node2
  node-exporter3:
    image: prom/node-exporter
    container_name: node-exporter3
    ports:
      - "9100"
    networks:
      - pi_network

  node4:
    build:
      context: ./NODE
      dockerfile: Dockerfile
    container_name: node4-container
    environment:
      - NODE_ID=node4
      - NODE_PORT=8082
      - DATA_COLLECTOR_URL=http://data_collector:8001/receive_metrics
      - PROMETHEUS_URL=http://prometheus:9090
      - INSTANCE_LABEL=node-exporter4:9100
    ports:
      - "8085:8082"
    networks:
      - pi_network
    depends_on:
      - node3
  node-exporter4:
    image: prom/node-exporter
    container_name: node-exporter4
    ports:
      - "9100"
    networks:
      - pi_network
  
  node5:
    build:
      context: ./NODE
      dockerfile: Dockerfile
    container_name: node5-container
    environment:
      - NODE_ID=node5
      - NODE_PORT=8082
      - DATA_COLLECTOR_URL=http://data_collector:8001/receive_metrics
      - PROMETHEUS_URL=http://prometheus:9090
      - INSTANCE_LABEL=node-exporter5:9100
    ports:
      - "8086:8082"
    networks:
      - pi_network
    depends_on:
      - node4
  node-exporter5:
    image: prom/node-exporter
    container_name: node-exporter5
    ports:
      - "9100"
    networks:
      - pi_network


  # Serviços web com NGINX
  web1:
    image: nginx:latest
    container_name: web1
    volumes:
      - ./WEB/html:/usr/share/nginx/html
    networks:
      - pi_network

  web2:
    image: nginx:latest
    container_name: web2
    volumes:
      - ./WEB/html:/usr/share/nginx/html
    networks:
      - pi_network

  # NGINX reverso para balancear carga entre web1 e web2
  nginx:
    build: 
      context: ./WEB
      dockerfile: Dockerfile
    image: nginx:${NGINX_IMAGE_VERSION}
    container_name: nginx-container
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
    networks:
      - pi_network
  
  k6:
    build:
      context: ./k6-tester 
      dockerfile: Dockerfile  
    depends_on:
      - nginx  
    networks:
      - pi_network
  
  model:
    build:
      context: ./AI
      dockerfile: Dockerfile
    container_name: model-container
    volumes:
      - ./data_collector/prometheus_data:/app/prometheus_data  
      - ./AI/foo.png:/app/foo.pgn
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - pi_network


volumes:
  db_data:
  db_replica_data:
  
  
networks:
  pi_network:
    driver: bridge


