scrape_configs:
  - job_name: 'nodes'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 'node-exporter1:9100'
          - 'node-exporter2:9100'
          - 'node-exporter3:9100'
          - 'node-exporter4:9100'
          - 'node-exporter5:9100'

  - job_name: 'blackbox'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Pode ser ajustado para tcp_connect, icmp, etc.
    static_configs:
      - targets:
          - 'node-exporter1:9100'
          - 'node-exporter2:9100'
          - 'node-exporter3:9100'
          - 'node-exporter4:9100'
          - 'node-exporter5:9100'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Endereço do Blackbox Exporter