apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: PiCloud
    titer: web-app
    environment: dev

  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
