apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer
  selector:
    app: PiCloud
    tier: web-app
    environment: dev
  ports:
    - port: 80
      targetPort: 80

