FROM rust:latest

WORKDIR /api_service

# Instalar o diesel_cli
RUN cargo install diesel_cli --no-default-features --features postgres

# Copiar as migrações
COPY migrations ./migrations

# Copiar o script wait-for-it.sh
COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

# Definir o ponto de entrada
ENTRYPOINT ["/usr/local/bin/wait-for-it.sh", "db:5432", "--"]

# Comando padrão
CMD ["diesel", "migration", "run"]
