apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    spec:
      containers:
      - name: k6
        image: k6:latest
        command: ["k6", "run", "/path/to/your/test/script.js"]
      restartPolicy: Never
  backoffLimit: 4
