apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: picloud-web-node:latest  # Use the local Docker image name
        imagePullPolicy: Never          # Ensure Kubernetes uses the local image
        ports:
        - containerPort: 8082
        env:
          - name: NODE_ID
            value: node1
          - name: NODE_PORT
            value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
  selector:
    app: node
