FROM prom/node-exporter

# Copiar o script de supervisão
COPY supervise_node.sh /usr/local/bin/supervise_node.sh

# Dar permissão de execução ao script
RUN chmod +x /usr/local/bin/supervise_node.sh

# Definir o ponto de entrada para executar o script
ENTRYPOINT ["/usr/local/bin/supervise_node.sh"]
