apiVersion: v1
kind: Service
metadata:
  name: postgres-master-service
  labels:
    app: postgres
    role: master

spec:
  type: ClusterIP
  selector:
    app: postgres
    role: master

  ports:
    - protocol: TCP
      port: 5432        
      targetPort: 5432  
