apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: manelsilva/my-web:latest  # Ou a sua imagem personalizada
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: web-nginx-config
        configMap:
          name: web-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: web
