apiVersion: v1
kind: ConfigMap
metadata:
  name: web-nginx-config
data:
  default.conf: |
    upstream api_servers {
        server api-service:8080;
    }

    server {
      listen 80;
      
      # Rota para a API
      location /api/ {
          proxy_pass http://api_servers;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

