apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: test                      # Usuário do PostgreSQL
  POSTGRES_PASSWORD: test                   # Senha do PostgreSQL
  POSTGRES_DB: test                        # Banco de dados padrão

