apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: test                      
  POSTGRES_PASSWORD: test                  
  POSTGRES_DB: test                        

